[package]
authors = ["Ben Ruijl <benruyl@gmail.com>"]
categories = ["science"]
description = "A symbolic manipulation toolkit which aims to handle expressions with billions of terms, taking up terabytes of diskspace."
edition = "2021"
keywords = ["algebra", "symbolic", "manipulation", "mathematics", "physics"]
license-file = "License.md"
name = "symbolica"
readme = "Readme.md"
repository = "https://github/benruijl/symbolica"
version = "0.0.0"

[profile.dev-optim]
inherits = "dev"
opt-level = 2

[lib]
crate-type = ["cdylib", "rlib"]
name = "symbolica"

[dev-dependencies]
tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}

[dependencies.rug]
default-features = false
features = ["integer", "rational"]
version = "1.19"

[dependencies]
ahash = "0.8"
byteorder = "1.4"
bytes = "1.3"
colored = "2.0"
rand = "0.8"
smallvec = "1.1"
smartstring = "1.0"
tracing = {version = "0.1", features = ["max_level_trace", "release_max_level_warn"]}