[package]
author = "Ben Ruijl"
authors = ["Ben Ruijl <benruyl@gmail.com>"]
categories = ["science"]
description = "A symbolic manipulation toolkit which aims to handle expressions with billions of terms, taking up terabytes of diskspace."
edition = "2021"
keywords = ["algebra", "symbolic", "manipulation", "mathematics", "physics"]
license-file = "License.md"
name = "symbolica"
readme = "Readme.md"
repository = "https://github/benruijl/symbolica"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "symbolica"

[dependencies]
byteorder = "1.4"
bytes = "1.3"
smartstring = "1.0"
ahash = "0.8"
smallvec = "1.1"
